# First we list the students as strings"
puts "Students in my cohort (November) are listed below:"

puts "Tom Groombridge"
puts "Hannah Knights"
puts "Georgi Georgiev"
puts "Me!"
puts "Tom Shacham"
puts "Kumy Veluppillai"
puts "Jean-Baptiste Blanc"
puts "Nicky Keszler"
puts "James Graham"
puts "Bruce Steedman"
puts "Michael Fisher"
puts "Peter Kristo"
puts "Jeremy Marer"
puts "Giacomo Patella"
puts "Gianni Guitteaud"
puts "Asta Bevainyte"
puts "Erica Salvaneschi"
puts "Nisar Tahir"
puts "Anath abensour"
puts "Simon Woolf"
puts "James Brooke"
puts "Ken Scott"

student_count = 22
# Now, we print the total, print is used to ensure no new line is inserted
puts "Overall we have #{student_count} great students." 
